# Generated by Django 4.0 on 2021-12-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_favourite',
        ),
    ]
