# Generated by Django 4.0 on 2021-12-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_favourite',
        ),
    ]
